// Code generated by gen_gsref.go . DO NOT EDIT.

package document_test

var gsTextShowRawString = "CADABX"

// gsTextShowRaw holds, for each TestTextShowRaw case, the input parameters and
// the glyph x positions recorded during text layout.  The positions were
// validated with ghostscript at generation time; see gen_gsref.go.
var gsTextShowRaw = []textShowRawCase{
	{fontSize: 100, m: [6]float64{1, 0, 0, 1, 0, 0}, stretch: 1, want: []float64{10, 85, 160, 235, 310, 385}},
}

var gsTextShowRaw2String = ".MiAbc"
var gsTextShowRaw2FontSize float64 = 100

// gsTextShowRaw2 holds, for each PDF version and font sample, the glyph x
// positions recorded during text layout.  The positions were validated with
// ghostscript at generation time; see gen_gsref.go.
var gsTextShowRaw2 = map[string][]float64{
	"1.7/CFFComposite1":         {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"1.7/CFFComposite2":         {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"1.7/CFFComposite3":         {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"1.7/CFFSimple1":            {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"1.7/CFFSimple2":            {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"1.7/OpenTypeCFFComposite1": {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"1.7/OpenTypeCFFComposite2": {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"1.7/OpenTypeCFFComposite3": {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"1.7/OpenTypeCFFSimple1":    {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"1.7/OpenTypeCFFSimple2":    {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"1.7/OpenTypeGlyfComposite": {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"1.7/OpenTypeGlyfSimple":    {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"1.7/Standard":              {10, 37.800000000000004, 121.1, 143.29999999999998, 210, 265.6},
	"1.7/TrueTypeComposite":     {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"1.7/TrueTypeSimple":        {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"1.7/Type1a":                {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"1.7/Type1b":                {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"1.7/Type3":                 {10, 41.640625, 124.94140625, 149.599609375, 216.298828125, 271.9140625},
	"2.0/CFFComposite1":         {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"2.0/CFFComposite2":         {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"2.0/CFFComposite3":         {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"2.0/CFFSimple1":            {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"2.0/CFFSimple2":            {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"2.0/OpenTypeCFFComposite1": {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"2.0/OpenTypeCFFComposite2": {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"2.0/OpenTypeCFFComposite3": {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"2.0/OpenTypeCFFSimple1":    {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"2.0/OpenTypeCFFSimple2":    {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"2.0/OpenTypeGlyfComposite": {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"2.0/OpenTypeGlyfSimple":    {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"2.0/Standard":              {10, 37.800000000000004, 121.1, 143.29999999999998, 210, 265.6},
	"2.0/TrueTypeComposite":     {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"2.0/TrueTypeSimple":        {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"2.0/Type1a":                {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"2.0/Type1b":                {10, 41.6, 124.9, 149.6, 216.3, 271.90000000000003},
	"2.0/Type3":                 {10, 41.640625, 124.94140625, 149.599609375, 216.298828125, 271.9140625},
}
