// seehuhn.de/go/pdf - a library for reading and writing PDF files
// Copyright (C) 2024  Jochen Voss <voss@seehuhn.de>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package document_test

//go:generate go run gen_gsref.go

import (
	"fmt"
	"io"
	"math"
	"testing"

	"seehuhn.de/go/geom/matrix"

	"seehuhn.de/go/pdf"
	"seehuhn.de/go/pdf/document"
	"seehuhn.de/go/pdf/graphics/testcases"
	"seehuhn.de/go/pdf/internal/fonttypes"
)

func TestTextPos(t *testing.T) {
	for i, setup := range testcases.All {
		t.Run(fmt.Sprintf("%02d", i), func(t *testing.T) {
			page, err := document.WriteSinglePage(io.Discard, testcases.Paper, pdf.V1_7, nil)
			if err != nil {
				t.Fatal(err)
			}

			page.TextBegin()
			err = setup(page)
			if err != nil {
				t.Fatal(err)
			}
			x, y := page.State.GState.GetTextPositionDevice()

			expected := testcases.AllGhostscript[i]
			if math.Abs(x-expected.X) > 1 || math.Abs(y-expected.Y) > 1 {
				t.Fatalf("expected x=%f, y=%f, got x=%f, y=%f", expected.X, expected.Y, x, y)
			}
		})
	}
}

// textShowRawCase holds the input parameters and reference glyph x positions
// for one TestTextShowRaw case.  The values are generated by gen_gsref.go.
type textShowRawCase struct {
	fontSize float64
	m        [6]float64
	stretch  float64
	want     []float64
}

// TestTextShowRaw checks that the glyph x positions computed during text layout
// match the reference positions in gsTextShowRaw.  Those positions were
// validated with ghostscript by gen_gsref.go (showing the text in one call,
// glyph-by-glyph, and individually at these positions all render identically),
// so the test itself runs without ghostscript.
func TestTextShowRaw(t *testing.T) {
	testString := pdf.String(gsTextShowRawString)

	for i, c := range gsTextShowRaw {
		t.Run(fmt.Sprintf("%d", i), func(t *testing.T) {
			F := fonttypes.CFFSimple()
			page, err := document.WriteSinglePage(io.Discard, &pdf.Rectangle{URx: 200, URy: 120}, pdf.V1_7, nil)
			if err != nil {
				t.Fatal(err)
			}
			page.TextBegin()
			page.TextSetFont(F, c.fontSize)
			page.TextSetMatrix(matrix.Matrix(c.m))
			page.TextSetHorizontalScaling(c.stretch)
			page.TextFirstLine(10, 10)

			var got []float64
			for j := range testString {
				got = append(got, page.State.GState.TextMatrix[4])
				page.TextShowRaw(testString[j : j+1])
			}
			page.TextEnd()
			if err := page.Close(); err != nil {
				t.Fatal(err)
			}

			if len(got) != len(c.want) {
				t.Fatalf("got %d positions, want %d", len(got), len(c.want))
			}
			for k := range got {
				if got[k] != c.want[k] {
					t.Errorf("position %d: got %v, want %v", k, got[k], c.want[k])
				}
			}
		})
	}
}

// TestTextShowRaw2 checks that the glyph x positions computed during text
// layout match the reference positions in gsTextShowRaw2.  Those reference
// positions were validated with ghostscript by gen_gsref.go: rendering the
// glyphs sequentially and rendering them individually at these positions
// produce identical images.  This lets the test run without ghostscript.
func TestTextShowRaw2(t *testing.T) {
	testString := gsTextShowRaw2String
	for _, v := range []pdf.Version{pdf.V1_7, pdf.V2_0} {
		for _, sample := range fonttypes.All {
			key := fmt.Sprintf("%s/%s", v, sample.Label)
			t.Run(key, func(t *testing.T) {
				want, ok := gsTextShowRaw2[key]
				if !ok {
					t.Fatalf("no reference data for %q; run go generate", key)
				}

				got := textShowRaw2Positions(t, v, sample, testString)

				if len(got) != len(want) {
					t.Fatalf("got %d positions, want %d", len(got), len(want))
				}
				for i := range got {
					if got[i] != want[i] {
						t.Errorf("position %d: got %v, want %v", i, got[i], want[i])
					}
				}
			})
		}
	}
}

// textShowRaw2Positions lays out testString with the sample font and returns
// the glyph x positions recorded from the text matrix.  This is shared with
// gen_gsref.go (which additionally validates the positions with ghostscript).
func textShowRaw2Positions(t *testing.T, v pdf.Version, sample *fonttypes.Sample, testString string) []float64 {
	t.Helper()

	fontSize := gsTextShowRaw2FontSize
	F := sample.MakeFont()
	codec := F.Codec()
	var s pdf.String

	page, err := document.WriteSinglePage(io.Discard, &pdf.Rectangle{URx: 400, URy: 120}, v, nil)
	if err != nil {
		t.Fatal(err)
	}
	page.TextSetFont(F, fontSize)
	page.TextBegin()
	page.TextFirstLine(10, 10)

	var xx []float64
	for _, g := range page.TextLayout(nil, testString).Seq {
		xx = append(xx, page.State.GState.TextMatrix[4])
		code, ok := F.Encode(g.GID, g.Text)
		if !ok {
			t.Fatalf("cannot encode glyph ID %d (%q)", g.GID, g.Text)
		}
		s = codec.AppendCode(s[:0], code)
		page.TextShowRaw(s)
	}
	page.TextEnd()

	if err := page.Close(); err != nil {
		t.Fatal(err)
	}
	return xx
}
