// Code generated by ./generate.go .  DO NOT EDIT.

package testcases

var AllGhostscript = []Answer{
	{0.000000, 0.000000},
	{146.250000, 10.000000},
	{146.250000, 25.000000},
	{96.750000, 96.750000},
	{136.250000, 0.000000},
}
