// Code generated by seehuhn.de/go/pdf/internal/stdmtx/generate; DO NOT EDIT.

package stdmtx

import (
	"seehuhn.de/go/geom/rect"
	"seehuhn.de/go/pdf/font/pdfenc"

	"seehuhn.de/go/sfnt/os2"
)

// FontData contains metrics for one of the 14 standard fonts.
// All lengths are in PDF glyph space units.
type FontData struct {
	FontFamily   string
	FontWeight   os2.Weight
	IsFixedPitch bool
	IsSerif      bool
	IsSymbolic   bool
	FontBBox     rect.Rect
	ItalicAngle  float64
	Ascent       float64
	Descent      float64 // negative
	CapHeight    float64
	XHeight      float64
	StemV        float64
	StemH        float64

	Width map[string]float64

	Encoding []string
}

var Metrics map[string]*FontData = metrics

var (
	standardEncoding = pdfenc.Standard.Encoding[:]
	symbolEncoding   = pdfenc.Symbol.Encoding[:]
	zapfDingbatsEncoding = pdfenc.ZapfDingbats.Encoding[:]
)
